### ISSUE TITLE
Plugin Renamer failing with special characters such as é è à

### ISSUE THREAD

**Issue by yongbi85** [RuudBurger/CouchPotatoServer#4449] opened 2015-01-04 08:59 UTC
### Information:
Movie(s) I have this with: Any movie with characters such as é è à in the name (french movies), the renamer plugin fails
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 2f5526d5 (2015-01-02 18:54:36)
Running on: Synology

### Logs:
```
01-04 09:22:34 ERROR [tato.core.plugins.renamer] Failed renaming the file "Paris A Tout Prix 2013 FRENCH 720p BluRay x264-NERDHD.mkv" : Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 620, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/volume1/Videos/Movies/Paris \xc3\xa0 tout prix (2013)/Paris \xc3\xa0 tout prix (2013).mkv' 
```

**Comment by yongbi85** [comment] 2015-01-04 09:52
I should add that it also have the same behaviour inside the nfo file, i temporarly changed my renamer to imdb_id so it is at least able to move them and get the correct metadata, I then manually renamed them but even inside the nfo, any character like é è à are replaced by strange ones...
Does the issue lay with couchpotato (missing french library character ?) or with the NAS ? (though the NAS OS is in french with those special characters showing ok)

**Comment by mcwieger** [comment] 2015-01-04 12:45
Not exactly the same, but similar: a movie with an apostrofe in it (C'est ....) was stored as C only.

**Comment by ellismichaelc** [comment] 2015-01-18 03:10
Also having this issue.

[tato.core.plugins.renamer] Couldn't move file "/media/complete/movies/REC2.2009.Bluray.1080p.DTS-HD.x264-cp(tt1245112).mkv" to "/media/movies/[REC]Â˛ (2009)/[REC]Â˛ (2009) [1080p].mkv"

**Comment by gondrup** [comment] 2015-02-08 12:05
I also have this issue with any movies with special characters in the title.

### Information:
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 5b1dd686 (2015-01-17 12:04:58)
Running on: FreeBSD 8.2-RELEASE

There are no errors in the log that relate to the issue but "Les Misérables (2012)" does not get renamed. Also any movies with a colon in the title do not get renamed.

**Comment by skarekrow** [comment] 2015-02-08 12:21
That's odd, I have 10 movies with a colon in their name or many other movies with different characters. I'm running FreeBSD 10.1-RELEASE, you should think about updating. There could be something that is not functioning 100% and got fixed. I'm also on the same commit as @gondrup. Not sure why I cannot get less to make this more readable, so my apologies.  I don't have any errors but I'll post a log with the latest movie with a colon in it below:

`02-06 00:26:14 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/tt3306776/, data: []ESC[0m
02-06 00:26:14 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/tt3306776?api_key=xxx&append_to_response=alternative_titles, data: []
ESC[0m
02-06 00:26:14 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?i=tt3306776, data: []ESC[0m
02-06 00:26:14 INFO ESC[0m[ie.providers.info.omdbapi] Found: Bayonetta: Bloody Fate (2013)ESC[0m
02-06 00:26:14 INFO ESC[0m[tato.core.plugins.scanner] Found 1 movies in the folder /NAS/Torrents/Completed/MoviesESC[0m
02-06 00:26:14 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/ismovie/tt3306776/?adding=1, data: []ESC[0m
02-06 00:26:15 INFO ESC[0m[ie.providers.info.omdbapi] Found: Bayonetta: Bloody Fate (2013)ESC[0m
02-06 00:26:15 INFO ESC[0m[ie.providers.info.omdbapi] Found: Bayonetta: Bloody Fate (2013)ESC[0m
02-06 00:26:15 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get https://image.tmdb.org/t/p/w154/iB68dHMdUFBeci9FrDvnpd65zSy.jpg, data: []ESC[0m
02-06 00:26:16 INFO ESC[0m[tato.core.plugins.renamer] Moving "/NAS/Torrents/Completed/Movies/Bayonetta_-_Bloody_Fate_[BD_1080p][10bit][FLAC_5.1][Kaibrid].mkv" to "/NAS/Movies/Bayonetta Bloody Fate (2013)/Bayonetta Bloody Fate.mkv"ESC[0m
02-06 00:26:16 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get http://www.hd-trailers.net/movie/bayonetta-bloody-fate/, data: []ESC[0m
02-06 00:26:16 INFO ESC[0m[e.providers.metadata.base] Creating XBMC metadata.ESC[0m
02-06 00:26:16 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get http://webservice.fanart.tv/v3/movies/tt3306776?api_key=xxxESC[0m
02-06 00:26:16 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/tt3306776?api_key=xxx&append_to_response=alternative_titles%2Cimages%2Ccasts, data: []ESC[0m
02-06 00:26:16 INFO ESC[0m[ie.providers.info.omdbapi] Found: Bayonetta: Bloody Fate (2013)ESC[0m
02-06 00:26:16 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get https://image.tmdb.org/t/p/original/iB68dHMdUFBeci9FrDvnpd65zSy.jpg, data: []ESC[0m
02-06 00:26:17 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get https://image.tmdb.org/t/p/original/cHOLVIHgEfb40WdB1hddrhVtx3B.jpg, data: []ESC[0m
02-06 00:26:17 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get https://image.tmdb.org/t/p/original/oJsSmEapCE38ftb0sTbbBmdwamo.jpg, data: []ESC[0m
02-06 00:26:17 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get https://image.tmdb.org/t/p/original/7TrgM3msaDcBbEi7svyQhqqgPO2.jpg, data: []ESC[0m
02-06 00:26:17 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get https://image.tmdb.org/t/p/original/eYsJrffK4A5WFvSZt7D63MAPbZd.jpg, data: []ESC[0m
02-06 00:26:18 INFO ESC[0m[hpotato.core.plugins.base] Opening url: get https://image.tmdb.org/t/p/original/vbsGN50yIStWx76Ynb762mfJIVi.jpg, data: []ESC[0m
02-06 00:26:19 INFO ESC[0m[tato.core.plugins.scanner] Found 1 movies in the folder /NAS/Movies/Bayonetta Bloody Fate (2013)ESC[0m`

**Comment by JoaoRodrigues** [comment] 2015-02-09 02:07
The problem seems to be the ss method of core/helpers/encoding.py. The string is already in unicode with a particular encoding and it is re-encoded with whatever encoding Couchpotato finds in the settings, in my case, and default, UTF-8. This makes a mess out of the file name. 

A small test that reproduces the problem:
```python
name = u'Am\xe9lie (2001)'
name.encode('UTF-8')
'Am\xc3\xa9lie (2001)'
```

Not being an expert with unicode/byte strings, I got around it by adding the encoding.py method stripAccents to the return of ss method. The movie name is now 'sane', without any accents, but at least all problems are gone. 

Not a solution, but a hacky workaround..

**Comment by gondrup** [comment] 2015-02-09 09:58
@skarekrow: Upgrading the OS on my NAS has been on my to-do list for far too long (clearly) so I will make this a priority now and let you know if that fixes the issue for me.

**Comment by skarekrow** [comment] 2015-02-09 10:00
@gondrup :) Although I don't believe that will resolve the issue with Les Misérables (2012) as it seems @JoaoRodrigues has some good information on the issue. But I do think that may solve your issues with colons. Good luck nonetheless!

**Comment by McNetic** [comment] 2015-02-10 14:57
I also stumbled across this problem. It occurs multiple times in the code. If a unicode string is only fed once through ss(), the special characters only get messed up, if it gets fed twice, it results in the mentioned error.
@RuudBurger: I do not understand what's the reasoning behind first, having (mostly) all strings as unicode in the renamer, but then doing a ss() in doReplace() and in sp(). For testing, I removed the ss() calls from doReplace() and sp(), and everything appears to work as intended. If you could elaborate on your reasoning behind all this, I could try find the right (tm) solution to the problem (I personally think it would be most desirable to have all metadata related strings as unicode strings from the very beginning, so they don't get en/decoded back and forth throughout the process). I'd be willing to provide a full patch for the problem.

**Comment by adprom** [comment] 2015-02-28 00:39
Have the same issue on a DS2415+ here

**Comment by OverlordQ** [comment] 2015-03-15 06:42
Yeah, when it's read in first it should be decoded, it shouldn't be touched again internally until it needs to go out.

**Comment by davidrothera** [comment] 2015-03-17 16:32
Likewise also seeing this on OSX with Brew installed Python 2.7 on both Git and release version

**Comment by gondrup** [comment] 2015-04-11 14:26
@skarekrow: Just so you know I have upgraded my server to FreeBSD 10.1-RELEASE and movies with colon characters in the title are now renamed correctly. Thanks for your help.

**Comment by skarekrow** [comment] 2015-04-13 22:12
@gondrup That's great to hear!

**Comment by yuuzhan** [comment] 2015-04-17 15:40
Getting this issue on linux as well:
04-17 11:19:20 INFO ^[[0m[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i=tt0318403, data: []^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Setting cache omdbapi.cache.tt0318403^[[0m
04-17 11:19:21 INFO ^[[0m[ie.providers.info.omdbapi] Found: The Lion King 1 1/2 (2004)^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Setting cache eb424c28ca7213369f16f20a48d389ef^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Setting cache 414cf2397ec6a6e3b6ce1895e033402e^[[0m
04-17 11:19:21 DEBUG ^[[36m[   couchpotato.core.event] Return modified results for movie.info^[[0m
04-17 11:19:21 INFO ^[[0m[tato.core.plugins.scanner] Found 2 movies in the folder /media/ytorrent_dl/needSortMovies^[[0m
04-17 11:19:21 INFO ^[[0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/ismovie/tt0105935/?adding=1, data: []^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Setting cache d9a1dcfd9714cfa5bc1492cd82396105^[[0m
04-17 11:19:21 ERROR ^[[31m[to.core.media.movie._base] Can't add movie, seems to be a TV show.^[[0m
04-17 11:19:21 DEBUG ^[[36m[o.core.notifications.core] Notifying frontend^[[0m
04-17 11:19:21 DEBUG ^[[36m[o.core.notifications.core] Done notifying frontend^[[0m
04-17 11:19:21 ERROR ^[[31m[tato.core.plugins.renamer] Could not rename, no library item to work with: 1994 aladdin tt0105935^[[0m
04-17 11:19:21 INFO ^[[0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/ismovie/tt0318403/?adding=1, data: []^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Setting cache 54b26fd3a8ad61a379d7c6c2db0f4a22^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Getting cache 414cf2397ec6a6e3b6ce1895e033402e^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Getting cache omdbapi.cache.tt0318403^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Getting cache eb424c28ca7213369f16f20a48d389ef^[[0m
04-17 11:19:21 INFO ^[[0m[ie.providers.info.omdbapi] Found: The Lion King 1 1/2 (2004)^[[0m
04-17 11:19:21 DEBUG ^[[36m[   couchpotato.core.event] Return modified results for movie.info^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Acquiring lock: media.get.06f1192d77c8477ab525d66db8c0b147^[[0m
04-17 11:19:21 DEBUG ^[[36m[o.core.notifications.core] Notifying frontend^[[0m
04-17 11:19:21 DEBUG ^[[36m[o.core.notifications.core] Done notifying frontend^[[0m
04-17 11:19:21 DEBUG ^[[36m[ato.core.plugins.subtitle] Searching for subtitles for: [u'/media/ytorrent_dl/needSortMovies/2004 - The Lion King 1-1.5 - Hakuna Matata.(tt0318403).DVD-Rip.avi']^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Getting cache 414cf2397ec6a6e3b6ce1895e033402e^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Getting cache omdbapi.cache.tt0318403^[[0m
04-17 11:19:21 INFO ^[[0m[ie.providers.info.omdbapi] Found: The Lion King 1 1/2 (2004)^[[0m
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Getting cache eb424c28ca7213369f16f20a48d389ef^[[0m
04-17 11:19:21 DEBUG ^[[36m[   couchpotato.core.event] Return modified results for movie.info^[[0m
04-17 11:19:21 DEBUG ^[[36m[to.core.media.movie._base] Adding titles: [u'The Lion King 1\xbd', u'The Lion King 1 and A Half', u'The Lion King 1.5', u'The Lion King 1 & Half', u'O Rei Le\xe3o 3 Hakuna Matata', u'The Lion King 3: Hakuna$
04-17 11:19:21 DEBUG ^[[36m[hpotato.core.plugins.base] Releasing lock: media.get.06f1192d77c8477ab525d66db8c0b147^[[0m
04-17 11:19:21 DEBUG ^[[36m[   couchpotato.core.event] Assume disabled eventhandler for: scanner.remove_cptag^[[0m
04-17 11:19:21 DEBUG ^[[36m[   couchpotato.core.event] Assume disabled eventhandler for: scanner.remove_cptag^[[0m
04-17 11:19:21 DEBUG ^[[36m[tato.core.plugins.renamer] Media has no quality profile: The Lion King 1Â½^[[0m
04-17 11:19:21 DEBUG ^[[36m[tato.core.plugins.renamer] Removing leftover files^[[0m
04-17 11:19:21 INFO ^[[0m[tato.core.plugins.renamer] Moving "/media/ytorrent_dl/needSortMovies/2004 - The Lion King 1-1.5 - Hakuna Matata.(tt0318403).DVD-Rip.avi" to "/media/movies/Lion.King.1Â½,.The.(2004)[tt0318403]/The.Lion.King.1Â½04-17 11:19:21 ERROR ^[[31m[tato.core.plugins.renamer] Couldn't move file "/media/ytorrent_dl/needSortMovies/2004 - The Lion King 1-1.5 - Hakuna Matata.(tt0318403).DVD-Rip.avi" to "/media/movies/Lion.King.1ÃË
  File "/home/user/.couchpotato/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/media/movies/Lion.King.1\xc2\xbd,.The.(2004)[tt0318403]/The.Lion.King.1\xc2\xbd.(2004).[tt0318403].DVD-Rip.avi'
^[[0m
04-17 11:19:21 ERROR ^[[31m[tato.core.plugins.renamer] Failed renaming the file "2004 - The Lion King 1-1.5 - Hakuna Matata.(tt0318403).DVD-Rip.avi" : Traceback (most recent call last):
  File "/home/user/.couchpotato/couchpotato/core/plugins/renamer.py", line 620, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/home/user/.couchpotato/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/media/movies/Lion.King.1\xc2\xbd,.The.(2004)[tt0318403]/The.Lion.King.1\xc2\xbd.(2004).[tt0318403].DVD-Rip.avi'
^[[0m

**Comment by dramixx** [comment] 2015-05-05 08:58
Getting this issue with the special character "é" from the movie "The Bélier Family". This one can't be renamed and moved.

05-05 10:46:28ERROR[tato.core.plugins.renamer] Couldn't move file "/volume1/downloads/La.Famille.BĂŠlier.2014.French.1080p.HDLight-x264.GHT.mkv" to "/volume1/video/movie/La Famille BĂŠlier (2014) [1080p]/La Famille BĂŠlier.2014.1080p.x264.mkv": Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/volume1/video/movie/La Famille B\xc3\xa9lier (2014) [1080p]/La Famille B\xc3\xa9lier.2014.1080p.x264.mkv'

**Comment by JeremiahGillis** [comment] 2015-07-04 19:44
In my case of Alien 3, it does create a destination directory with incorrect text. See steps to reproduce.

### Steps to reproduce:
1. Restart server to scan Download folder for new movies.
2. Set renamer to folder naming: <thename> (<year>) and file naming: <thename>.<imdb_id>.<quality>.<3d_type>.<ext>
3. Contain Alien 3 in Download folder, name it "Alien 3.tt0103644.DTS.mkv". It actually had a superscript 3, but I removed it thinking that might be the issue. Also had trouble finding the movie on imdb without the tt info.
4. CP will create a folder in destination called "AlienÂł (1992)" and will fail to rename / move the movie.

### Information:
Movie(s) I have this with: Alien 3
Quality of the movie being searched: Was not search, manually added the movie into download folder.
Providers I use: NA, but Oznzb and Supernews
Version of CouchPotato: source:(RuudBurger:CouchPotatoServer master) 69825f9d (2015-05-27 13:06:41)
Running on: FreeNAS, FreeBSD, using Windows 8.1 to add movie to download folder.

### Logs:
```
07-04 14:24:36  INFO [ie.providers.info.omdbapi] Found: AlienÂł (1992) 
07-04 14:24:36  INFO [ie.providers.info.omdbapi] Found: AlienÂł (1992) 
07-04 14:24:36  INFO [tato.core.plugins.renamer] Moving "/media/Download/Alien 3.tt0103644.DTS.mkv" to "/media/Movies/AlienÂł (1992)/AlienÂł.tt0103644.1080p.mkv" 
07-04 14:24:36 ERROR [tato.core.plugins.renamer] Couldn't move file "/media/Download/Alien 3.tt0103644.DTS.mkv" to "/media/Movies/AlienÂł (1992)/AlienÂł.tt0103644.1080p.mkv": Traceback (most recent call last):
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/media/Movies/Alien\xc2\xb3 (1992)/Alien\xc2\xb3.tt0103644.1080p.mkv' 
07-04 14:24:36 ERROR [tato.core.plugins.renamer] Failed renaming the file "Alien 3.tt0103644.DTS.mkv" : Traceback (most recent call last):
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 620, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/media/Movies/Alien\xc2\xb3 (1992)/Alien\xc2\xb3.tt0103644.1080p.mkv' 
07-04 14:24:36 ERROR [hpotato.core.plugins.base] Unable writing to file "/media/Download/Alien 3.tt0103644.DTS.failed_rename.ignore": Traceback (most recent call last):
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/base.py", line 146, in createFile
    os.chmod(path, Env.getPermission('file'))
OSError: [Errno 1] Operation not permitted: '/media/Download/Alien 3.tt0103644.DTS.failed_rename.ignore' 
```

**Comment by skarekrow** [comment] 2015-07-05 06:29
@JeremiahGillis that is not the same error. You are getting a permissions error, and it looks like you're doing this with a freenas plugin. Make sure you don't have ACL's enabled on the dataset. If you made the dataset with windows permissions then you have them enabled. 

To remove them do this:
```find /folder/location -type f -exec setfacl -b {} +```
and 
```find /folder/location -type d -exec setfacl -b {} +```

Witness your error disappear! ;)

**Comment by JeremiahGillis** [comment] 2015-07-06 14:38
@skarekrow Thanks for the information. This fixed my issue with other movies. I manually moved Alien 3.

**Comment by skarekrow** [comment] 2015-07-07 00:17
@JeremiahGillis No problem.

**Comment by Smultie** [comment] 2015-07-14 18:20
Same issue here (Raspberry Pi, XBian Jessie):
https://github.com/RuudBurger/CouchPotatoServer/issues/5141

**Comment by Dam4rusxp** [comment] 2015-07-22 14:22
I have this problem too and it took way longer than it should have to pinpoint, where it comes from. 

These are the lines, that result in the malformed pathnames, when calling the sp method:
```python
# couchpotato.core.helpers.encoding
def sp(path, *args):
    [...]
    path = os.path.normpath(ss(path, *args))
    [...]

def ss(original, *args):
    u_original = toUnicode(original, *args)
    [...]

def toUnicode(original, *args):
    [...]
    return six.text_type(original, *args)
    [...]
```

Now you have to know that `six.text_type` is `unicode`, when running Python 2, and sp gets passed a str encoded in UTF-8. So we are creating an Unicode object, by passing the unicode constructor a UTF-8 string. AFAIK this is NOT the correct way to do it. Correct would be `original.decode("UTF-8")` or better `original.decode(Env.get('encoding'))`. This is basically what happens if the direct conversion to unicode fails (In an except block after the problematic line), but that will probably never happen, except for really badly corrupted strings.

Alright, now that I've written my thoughts on this down, I'm trying to fix it.

**Comment by Dam4rusxp** [comment] 2015-07-22 15:40
I think I managed to fix toUnicode. Metadata is still not working, but the Movie and NFO files get the correct name.

```python
def toUnicode(original, *args):
    try:
        if isinstance(original, unicode):
            return original
        else:
            try:
                return six.text_type(original, *args)
            except:
                try:
                    from couchpotato.environment import Env
                    return original.decode(Env.get("encoding"))
                except:
                    try:
                        detected = detect(original)
                        try:
                            if detected.get('confidence') > 0.8:
                                return original.decode(detected.get('encoding'))
                        except:
                            pass

                        return ek(original, *args)
                    except:
                        raise
    except:
        log.error('Unable to decode value "%s..." : %s ', (repr(original)[:20], traceback.format_exc()))
        return 'ERROR DECODING STRING'
```

**Comment by tonybeccar** [comment] 2015-07-26 18:18
Hi!

I have a raspberry pi with Openelec.. I was wondering when will this fix be merged with the master branch? Because I don't know how to enable the develop branch from openelec, or if it's possible somehow...

Thanks!!!

**Comment by jrozelle** [comment] 2015-09-15 21:28
Same issue here, on master branch, up-to-date.
Thanks in advance !

**Comment by jrozelle** [comment] 2015-09-25 08:09
@dramixx : I found a solution for this movie : I add an alternative title in tmdb, without special character.

**Comment by timrettop** [comment] 2015-10-01 21:25
Is this the same bug for file names that include a dash "-"?  

I get the following error:  

'''
10-01 14:14:22 INFO [tato.core.plugins.renamer] Moving "/belly/newsbin/complete/movies/Mission.Impossible.Ghost.Protocol.2011.720p.iNTERNAL.BluRay.x264-FFM.cp(tt1229238)/Mission.Impossible.4.Ghost.Protocol.2011.720p.iNTERNAL.BluRay.x264-FFM.mkv" to "/belly/movies/Mission Impossible – Ghost Protocol (2011)/Mission Impossible – Ghost Protocol.mkv"
10-01 14:14:22 ERROR [tato.core.plugins.renamer] Couldn't move file "/belly/newsbin/complete/movies/Mission.Impossible.Ghost.Protocol.2011.720p.iNTERNAL.BluRay.x264-FFM.cp(tt1229238)/Mission.Impossible.4.Ghost.Protocol.2011.720p.iNTERNAL.BluRay.x264-FFM.mkv" to "/belly/movies/Mission Impossible – Ghost Protocol (2011)/Mission Impossible – Ghost Protocol.mkv": Traceback (most recent call last):
  File "/home/tim/.couchpotato/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/belly/movies/Mission Impossible \xe2\x80\x93 Ghost Protocol (2011)/Mission Impossible \xe2\x80\x93 Ghost Protocol.mkv'

10-01 14:14:22 ERROR [tato.core.plugins.renamer] Failed renaming the file "Mission.Impossible.4.Ghost.Protocol.2011.720p.iNTERNAL.BluRay.x264-FFM.mkv" : Traceback (most recent call last):
  File "/home/tim/.couchpotato/couchpotato/core/plugins/renamer.py", line 620, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/home/tim/.couchpotato/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/belly/movies/Mission Impossible \xe2\x80\x93 Ghost Protocol (2011)/Mission Impossible \xe2\x80\x93 Ghost Protocol.mkv'

'''

**Comment by jrozelle** [comment] 2015-10-02 11:33
same problem for this movie, but this in not a dash "-".
I don't know his name in english : it's not a simple dash, but a larger one. (simple dash : "‒". Other dash :   "–"  "—"  "―").

Select an alternative title in CP and everything will be ok :-)

**Comment by MaximePeron** [comment] 2015-10-06 15:35
I had the same issue with special characters (é, è, à, ...)

I temporarily fixed it by changing one line of code in "couchpotato/core/plugins/renamer.py" in method toUnicode
return original.decode(detected.get('encoding')) 
to 
return original.decode('UTF-8')

Not a good solution, but seems to work for me.

**Comment by dramixx** [comment] 2015-10-14 14:53
@jrozelle OK thanks that works ! a temporary solution would be to change the title with a no accent title ;)

**Comment by RuudBurger** [comment] 2015-12-10 14:39
Fixed in develop

**Closed by RuudBurger** 2015-12-10 14:39 UTC
Labels: 1 - Prioritize, 3 - Bug
